import type { ProjectData } from "@types";
import Image from "@components/Image/Image";
import Link from "@components/Link/Link";
import Video from "@components/Video/Video";
import Cover from "./Cover.png";
import Matchup from "./Matchup.png";
import Paris2024 from "./Paris2024.png";
import MatchupDemo from "./MatchupDemo.mp4";
import TotalMatchups from "./TotalMatchups.png";
import Shadows from "./Shadows.png";
import ShadowDemo from "./ShadowDemo.mp4";
import TotalShadows from "./TotalShadows.png";

const VisMerchEditor: ProjectData = {
  title: "Vis Merch Editor",
  subTitle: "Figma plugin for Peacock Editorial",
  coverImageSrc: Cover,
  coverPosition: "center",
  passwordRequired: false,
  overview: {
    problem:
      "Editorial teams need a way to quickly create and customize sports assets created by Peacock designers.",
    goal: "Automate the creation of sports assets with a Figma plugin.",
    outcome:
      "In 2025 the plugin had 22 active users that generated a combined 46,000 assets.",
    role: "I was the lead developer on this project.",
    technologies: "Figma Plugin API, TypeScript, React",
    dates: "February 2024 - present",
  },
  content: (
    <>
      <p>
        This plugin contains multiple features for creating sports assets,
        including Team Matchup and Shadow Creator. This work was a partnership
        between my Design Engineering team and the Visual Merchandising team at
        Peacock.
      </p>

      <h2>Team Matchup</h2>

      <p>
        In the spring of 2024 when I first joined Peacock, the design team was
        preparing for the Summer Olympics 2024. They anticipated a need to
        generate thousands of tile art images to illustrate all the country
        matchups for the various sports events. This would be a time consuming
        and manual process for the editorial team that curates these tiles.
        However, they recognized the power that a Figma plugin could have in
        automating this work. I was tasked with building out this plugin
        functionality.
      </p>

      <Image src={Matchup} />

      <p>
        The plugin automates the work of importing the template component,
        swapping out the country flags and sports icon, updating the background
        color, giving the layer a standardized name, and adding default export
        settings. It generates every possible country matchup, including
        variations for which position the country flag is in. For some sports
        with a lot of participating countries there may be up to 3000 assets
        generated at once.
      </p>

      <Image
        src={Paris2024}
        caption="Example of tiles this plugin created in product during the Paris 2024 Olympics"
      />

      <p>
        Performance was a key concern, so I made sure to optimize the plugin to
        handle these large batches of assets efficiently using strategies like{" "}
        <Link href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all">
          Promise.all
        </Link>{" "}
        and briefly pausing the execution of the plugin to allow Figma to render
        the changes.
      </p>

      <p>
        After the Olympics work was complete, I leveraged this functionality for
        other sports matchups such as NBA, NFL, NHL, Premier League, and more.
        Designers could manage a file with these logos and the plugin would
        automatically pull these updates to create the matchup templates.
      </p>

      <Video
        src={MatchupDemo}
        caption="Demo of creating both 2026 Olympics and other sports matchups in the plugin."
      />

      <p>
        I added <Link href="https://mixpanel.com/">Mixpanel analytics</Link> to
        track our plugin users, what they were generating, and any errors.
      </p>

      <Image
        src={TotalMatchups}
        caption="Total assets generated by the plugin during the Summer 2024 Olympics"
      />

      <h2>Shadow Creator</h2>

      <p>
        Building on the success of the Team Matchup feature, the Visual
        Merchandising team and I partnered again to make the Shadow Creator. The
        goal of this feature was to automate placing shadows behind clipped
        human figures in composite sports assets. The benefit of automating this
        work meant that the finished assets would more closely align with the
        design guidelines and that the editorial team would have more time to
        focus on other tasks.
      </p>

      <Image src={Shadows} />

      <p>
        I suggested that instead of building a brand new plugin, we could extend
        the existing Team Matchup plugin to include this functionality as a
        separate page. It would benefit the end users by having fewer plugins to
        manage, and make it faster for developers to add new functionality. This
        strategy ended up being very successful and allowed my team to add a
        third feature to the plugin later on.
      </p>

      <p>
        To use this feature, the user starts by uploading 1-3 images of athletes
        with transparent backgrounds. The plugin processes these images to add
        shadows behind them, and masks and groups layers so shadows are clipped
        to their subjects. The plugin positions and scales the images by
        default, but it is expected that the user may need to make tweaks to
        perfect the composition.
      </p>

      <p>
        Once the user has made the necessary changes, they need to run the
        plugin again to update the shadows. When generating shadows we save data
        about the images to each layer, so the plugin is able to find and reuse
        this data when regenerating shadows.
      </p>

      <Video src={ShadowDemo} caption="Demo of the Shadow Creator in action" />

      <p>
        I added Mixpanel analytics to track the usage of this page in the
        plugin.
      </p>

      <Image
        src={TotalShadows}
        caption="Total shadow generation and regeneration events in 2025"
      />
    </>
  ),
};

export default VisMerchEditor;
