import type { ProjectData } from "@types";
import Image from "@components/Image/Image";
import Link from "@components/Link/Link";
import Video from "@components/Video/Video";
import Cover from "./Cover.png";
import Matchup from "./Matchup.png";
import Paris2024 from "./Paris2024.png";
import MatchupDemo from "./MatchupDemo.mp4";
import TotalMatchups from "./TotalMatchups.png";
import Shadows from "./Shadows.png";
import ShadowDemo from "./ShadowDemo.mp4";
import TotalShadows from "./TotalShadows.png";

const VisMerchEditor: ProjectData = {
  title: "Vis Merch Editor",
  subTitle: "Figma plugin for Peacock Editorial",
  coverImageSrc: Cover,
  coverPosition: "center",
  passwordRequired: false,
  overview: {
    problem:
      "Editorial teams need a way to quickly create and customize sports assets created by Peacock designers.",
    goal: "Automate the creation of sports assets with a Figma plugin.",
    outcome:
      "In 2025 the plugin had 22 active users that generated a combined 46,000 assets.",
    role: "I was the lead developer on this project.",
    technologies: "Figma Plugin API, TypeScript, React",
    dates: "February 2024 - present",
  },
  content: (
    <>
      <p>
        This plugin includes multiple features for creating sports assets,
        including Team Matchup and Shadow Creator. The work was a collaboration
        between my Design Engineering team and the Visual Merchandising team at
        Peacock.
      </p>

      <h2>Team Matchup</h2>

      <p>
        In spring 2024, when I first joined Peacock, the design team was
        preparing for the 2024 Summer Olympics. They anticipated a need to
        generate thousands of tile art images to represent country matchups
        across various sporting events. This would have been a time-consuming,
        manual process for the editorial team responsible for curating these
        tiles. We recognized the potential of a Figma plugin to automate this
        work, and I was tasked with building this functionality.
      </p>

      <Image src={Matchup} />

      <p>
        The plugin automates importing the template component, swapping country
        flags and sport icons, updating background colors, applying standardized
        layer names, and adding default export settings. It generates every
        possible country matchup, including variations for flag positioning. For
        sports with many participating countries, the plugin can generate up to
        3,000 assets in a single run.
      </p>

      <Image
        src={Paris2024}
        caption="Example of tiles this plugin created in product for the Paris 2024 Olympics"
      />

      <p>
        Performance was a key concern, so I made sure to optimize the plugin to
        handle these large batches of assets efficiently using strategies like{" "}
        <Link href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all">
          Promise.all
        </Link>{" "}
        and briefly pausing the execution of the plugin to allow Figma to render
        the changes.
      </p>

      <p>
        After the Olympics, I extended this functionality to support other
        sports, including the NBA, NFL, NHL, Premier League, and more. Designers
        could manage a file containing team logos, and the plugin would
        automatically pull updates to generate matchup templates.
      </p>

      <Video
        src={MatchupDemo}
        caption="Demo of creating both 2026 Olympics and other sports matchups in the plugin."
      />

      <p>
        I added <Link href="https://mixpanel.com/">Mixpanel analytics</Link> to
        track plugin usage, including what users generated and any errors
        encountered.
      </p>

      <Image
        src={TotalMatchups}
        caption="Total assets generated by the plugin during the Summer 2024 Olympics"
      />

      <h2>Shadow Creator</h2>

      <p>
        Building on the success of the Team Matchup feature, I partnered again
        with the Visual Merchandising team to create Shadow Creator. The goal
        was to automate placing shadows behind clipped human figures in
        composite sports assets. Automating this process ensured closer
        adherence to design guidelines and freed up editorial time for
        higher-value work.
      </p>

      <Image src={Shadows} />

      <p>
        Rather than building a new plugin, I proposed extending the existing
        Team Matchup plugin with this functionality as a separate page. This
        approach reduced plugin management for users and made it faster for
        developers to add new features. The strategy proved successful and later
        enabled my team to add a third feature to the plugin.
      </p>

      <p>
        To use Shadow Creator, users upload one to three athlete images with
        transparent backgrounds. The plugin adds shadows behind each subject,
        masks and groups layers so shadows remain clipped, and applies default
        positioning and scaling. Users can make manual adjustments to fine-tune
        the composition.
      </p>

      <p>
        After edits are complete, users rerun the plugin to regenerate shadows.
        The plugin stores metadata on each image layer, allowing it to reuse
        this data when updating shadows.
      </p>

      <Video src={ShadowDemo} caption="Demo of the Shadow Creator in action" />

      <p>I added Mixpanel analytics to track usage of this feature.</p>

      <Image
        src={TotalShadows}
        caption="Total shadow generation and regeneration events in 2025"
      />
    </>
  ),
};

export default VisMerchEditor;
